name = "psynex-exambot"
main = "src/index.js"
compatibility_date = "2025-10-23"

[durable_objects]
bindings = [
  { name = "ROOMS", class_name = "RoomDO" }
]

[[migrations]]
tag = "v1-sqlite"
new_sqlite_classes = ["RoomDO"]

# ๐ข ูุชุบุฑูุง ุบุฑุญุณุงุณ ฺฉู ุจุงุฏ ุจุนุฏ ุงุฒ ูุฑ ุฏูพูู ุจุงู ุจูุงููุฏ
[vars]
BOT_USERNAME = "psynex_exambot"
REQUIRED_CHANNEL = "@psynex"

[[r2_buckets]]
binding = "QUESTIONS"              # โ ุงู ุจุงุฏ QUESTIONS ุจุงุดุฏ
bucket_name = "exambot-questions"  # โ ุงุณู ูุงูุน ุจุงฺฉุช ุดูุง
